version: '3'

services:
  db:
    image: mysql:latest
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: your_root_password_here
      MYSQL_DATABASE: your_database_name_here
      MYSQL_USER: your_mysql_username_here
      MYSQL_PASSWORD: your_mysql_password_here
    ports:
      - 3306:3306
    volumes:
      - ./data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    environment:
      PMA_HOST: db
      PMA_USER: your_mysql_username_here
      PMA_PASSWORD: your_mysql_password_here
    ports:
      - 8080:80
